ecommerce/demo/urls.py
from django.contrib import admin
from django.urls import path

from ecommerce.demo import views

app_name = "demo"

urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.categoty, name="categories"),
    path(
        "product-by-category/<slug:category>/",
        views.product_by_category,
        name="product_by_category",
    ),
    path("<slug:slug>/", views.product_detail, name="product_detail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path

# from django_registration.backends.activation.views import RegistrationView

# from ecommerce.ecommerce_auth import views
# from ecommerce.ecommerce_auth.forms import EcommerceRegistrationForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("ecommerce.ecommerce_auth.urls")),
    # Registration
    # path(
    #     "accounts/register/",
    #     RegistrationView.as_view(form_class=EcommerceRegistrationForm),
    #     name="django_registration_register",
    # ),
    # path("accounts/", include("django_registration.backends.activation.urls")),
    # path("accounts/profile/", views.profile, name="profile"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("demo/", include("ecommerce.demo.urls", namespace="demo")),
    path("api/v1/", include("ecommerce.drf.urls", namespace="drf")),
    path("dninja/", include("ecommerce.dninja.urls", namespace="dninja")),
    path("", include("ecommerce.cbv.urls", namespace="cbv")),
    path("basket/", include("ecommerce.basket.urls", namespace="basket")),
]

ecommerce/demo/views.py
from django.shortcuts import render
from ecommerce.inventory import models


def home(request):

    return render(request, "index.html")


def categoty(request):
    all_data = models.Category.objects.all()

    print(all_data.query)

    return render(request, "categories.html", {"all_data": all_data})


def product_by_category(request, category):

    print(category)
    all_data = models.Product.objects.filter(category__name=category).values(
        "id", "name", "slug", "category__name", "product__store_price"
    )

    # all_data = models.ProductInventory.objects.filter(product__category__name=category)
    print(all_data.query)

    return render(request, "product_by_category.html", {"all_data": all_data})


def product_detail(request, slug):
    from django.contrib.postgres.aggregates import ArrayAgg
    from django.db.models import Count
    filter_arguments = []

    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)
        # print(filter_arguments)

        # all_data = models.Product.objects.filter(slug=slug)
        # all_data = models.ProductInventory.objects.filter(product__slug=slug).values(
        #     "id", "sku", "product__name", "store_price", "product_inventory__units"
        # )

        # all_data = (
        #     models.ProductInventory.objects.filter(product__slug=slug)
        #     .filter(attribute_values__attribute_value="red")
        #     .filter(attribute_values__attribute_value=5)
        #     .select_related("product")
        # ).values(
        #     "id", "sku", "product__name", "store_price", "product_inventory__units"
        # )

        # all_data = (
        #     models.ProductInventory.objects.filter(product__slug=slug).filter(
        #         attribute_values__attribute_value__in=filter_arguments
        #     )
        # ).values("id", "sku", "product__name", "store_price", "product_inventory__units")

        # all_data = (
        #     models.ProductInventory.objects.filter(product__slug=slug)
        #     .filter(attribute_values__attribute_value=filter_arguments[0])
        #     .filter(attribute_values__attribute_value=filter_arguments[1])
        # ).values("id", "sku", "product__name", "store_price", "product_inventory__units")

        # all_data = (
        #     models.ProductInventory.objects.filter(product__slug=slug)
        #     .filter(attribute_values__attribute_value__in=filter_arguments)
        #     .annotate(num_tags=Count("attribute_values"))
        #     .filter(num_tags=len(filter_arguments))
        # ).values(
        #     "id", "sku", "product__name", "store_price", "product_inventory__units"
        # )
        all_data = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(attribute_values__attribute_value__in=filter_arguments)
            .annotate(num_tags=Count("attribute_values"))
            .filter(num_tags=len(filter_arguments))
        ).values(
            "id", "sku", "product__name", "store_price", "product_inventory__units"
        ).annotate(field=ArrayAgg("attribute_values__attribute_value")).get()
        print(all_data)

    else:

        # all_data = (
        #     models.ProductInventory.objects.filter(product__slug=slug).values(
        #         "id", "sku", "product__name", "store_price", "product_inventory__units"
        #     ).annotate(filed = ArrayAgg("attribute_values__attribute_value")
        #     )
        # )

        all_data = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(is_default=True)
            .values(
                "id", "sku", "product__name", "store_price", "product_inventory__units"
            )
            .annotate(field=ArrayAgg("attribute_values__attribute_value")).get()
        )

        print(all_data)

    dump_one = (
        models.ProductInventory.objects.filter(product__slug=slug)
        .distinct()
        .values(
            "attribute_values__product_attribute__name",
            "attribute_values__attribute_value",
        )
    )
    # print(dump_one)

    dump_two = (
        models.ProductTypeAttribute.objects.filter(
            product_type__product_type__product__slug=slug
        )
        .values("product_attribute__name")
        .distinct()
    )
    # print(dump_two)

    return render(
        request,
        "product_detail.html",
        {"all_data": all_data, "dump_one": dump_one, "dump_two": dump_two},
    )


# https://docs.djangoproject.com/en/4.1/ref/models/expressions/
# Reporter.objects.update(stories_filed=F('stories_filed') + 1)

templates/demo/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.rtl.min.css"
      integrity="sha384-7mQhpDl5nRA5nY9lr8F1st2NbIly/8WqhjTp+0oFxEA/QUuvlbF6M1KXezGBh3Nb"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <title></title>
  </head>
  <body>
    {% block content %}{% endblock content %}
  </body>
</html>

templates/demo/categories.html
{% extends 'base.html' %} {% block content %}
<h1>Categories</h1>

{% for data in all_data %}
<li>
  <a href="{% url 'demo:product_by_category' category=data.slug%}"
    >{{data.name}}</a
  >
</li>
{% endfor %} {% endblock content %}

templates/demo/index.html
{% extends 'base.html' %} {% block content %}

<h1>Homepage</h1>
<a href="categories/"> Categories </a>

{% endblock content %}

templates/demo/product_by_category.html
{% extends 'base.html' %} {% block content %}
<h1>Product By Category</h1>

{% for data in all_data %}
<li>
  {{data.name}} - [<a href="{% url 'demo:product_detail' slug=data.slug %}">View Details</a>]
</li>
<li>{{data.id}}</li>
<li>Price: ${{data.product__store_price}}</li>
<br />
{% endfor %} {% endblock content %}

templates/demo/product_detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>Product Details:</h1>
{% comment %} {% for data in all_data %}
    <li>Product Name: {{data.product__name}}</li>
    <li>SKU: {{data.sku}}</li>
    <li>Store Price: {{data.store_price}}</li>
    <li>Units: {{data.product_inventory__units}}</li>
    <br/>

{% endfor %} {% endcomment %}

<ul>
    <li>Product Name: {{all_data.product__name}}</li>
    <li>SKU: {{all_data.sku}}</li>
    <li>Store Price: {{all_data.store_price}}</li>
    <li>Units: {{all_data.product_inventory__units}}</li>
    <br/>
</ul>
<ul>
    {% for data_one in dump_two %}
    <li>
        <h5>{{data_one.product_attribute__name}}</h5>
        <ul>
        {% for data_two in dump_one %}
            {% if data_two.attribute_values__product_attribute__name == data_one.product_attribute__name %}
            <li>
            {% if data_two.attribute_values__attribute_value in all_data.field %}
                <div id="target-{{data_two.attribute_values__attribute_value}}"
                class="selected fw-bold" data-attribute="{{data_one.product_attribute__name}}"
                value="{{data_two.attribute_values__attribute_value}}">{{data_two.attribute_values__attribute_value}}</div>
            {% else %}
                    <div id="target-{{data_two.attribute_values__attribute_value}}"
                    class="" data-attribute="{{data_one.product_attribute__name}}"
                    value="{{data_two.attribute_values__attribute_value}}">{{data_two.attribute_values__attribute_value}}</div>
            {% endif %}
            </li>
        {% endif %}
        {% endfor %}
        </ul>
        </li>
        <br>
    {% endfor %}
</ul>

<script>

    var dict = {}

    let boxId = document.querySelectorAll('[id^=target]');

    let counter = 0
    let boxLenght = boxId.length

    for(let i in boxId){
        if(counter < boxLenght){
            if(boxId[i].classList.contains("selected")){
                dict[boxId[i].getAttribute('data-attribute')] = boxId[i].getAttribute('value')
            }
        }else{
            break
        } counter++
    }

    $('[id^=target]').click(function(){
        let value = this.getAttribute('value');
        let dataAttribute = this.getAttribute('data-attribute');
        dict[dataAttribute] = value;

        const querystring = buildUrlWithParams(dict)
        const url = window.location.href.split('?')[0]

        window.location.href = url + '?' + querystring;
    });


    function buildUrlWithParams(data){
        var searchParams = [];
        
        for(var d in data){
            searchParams.push(d + '=' + data[d]);
        }
        return searchParams.join('&');
    }
</script>
{% endblock content %}